q=int(input("enter the prime number:"))
x1=int(input("enter 1st secret key:"))
x2=int(input("enter 2nd secret key:"))
for i in range(1,q):
    l=[]
    for j in range(0,q-1):
        l.append((pow(i,j))%q)
    if(len(l)==len(set(l))):
        a=i
        break
y1=(pow(a,x1))%q
y2=(pow(a,x2))%q
print("key generated by member1:",end="")
k=(pow(y2,x1))%q
print(k)
print("key generated by member2:",end="")
k=(pow(y1,x2))%q
print(k)


#11
#8
#7
